Controllers/OAuthController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using OAuthApp.Data;
using OAuthApp.Models;
using OAuthApp.Tenant;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Net;

namespace OAuthApp.Controllers
{
    public class OAuthController : Controller
    {
        private readonly ILogger<OAuthController> _logger;
        private readonly IMemoryCache _cache;
        private readonly TokenProvider _tokenProvider;
        private readonly ITenantUser _tenantUser;
        private TenantContext _tenant;
        private readonly AppDbContext _context;
        private readonly IDataProtector _dp;

        public OAuthController(ILogger<OAuthController> logger,
            IMemoryCache cache,
            TokenProvider tokenProvider,
            IHttpContextAccessor contextAccessor,
            ITenantUser tenantUser,
            AppDbContext context,
            IDataProtectionProvider dp)
        {
            _logger = logger;
            _cache = cache;
            _tenant = contextAccessor.HttpContext.GetTenantContext();
            _tokenProvider = tokenProvider;
            _tenantUser = tenantUser;
            _context = context;
            _dp = dp.CreateProtector(GetType().FullName);
        }

        [Authorize(JwtBearerDefaults.AuthenticationScheme)]
        public JsonResult UserInfo()
        {
            return Json(_tokenProvider.User);
        }

        [Authorize]
        public IActionResult Consent([FromQuery][Required]string code)
        {
            var authCode = _cache.Get<AuthorizationCode>(code);

            if (authCode == null)
            {
                return Json(new { code = 500, err = "授权码过期" });
            }

            var clientItem = _context.Apps.FirstOrDefault(x => x.AppKey.Equals(authCode.client_id));

            if (clientItem == null)
            {
                return Json(new { code = 500, err = "应用" + authCode.client_id + "不存在" });
            }

            var _redirect_uri = authCode.redirect_uri.Split('?')[0].ToLower();

            if (_context.UserConsents.Any(x =>
             x.UserID == authCode.userId &&
             x.UserGroup == UserDataGroups.System &&
             x.AppKey == authCode.client_id &&
             x.RedirectUri == _redirect_uri))
            {
                var url = WebUtility.UrlDecode(authCode.redirect_uri);

                _cache.Remove(code);

                return new RedirectResult(url);
            }
            else
            {
                ViewBag.client = clientItem;

                return View(authCode);
            }
        }

        [Authorize]
        [HttpPost]
        public IActionResult ConsentPost(string code)
        {
            var authCode = _cache.Get<AuthorizationCode>(code);

            var url = WebUtility.UrlDecode(authCode.redirect_uri);

            _context.UserConsents.Add(new UserConsent()
            {
                AppKey = authCode.client_id,
                Scope = authCode.scope,
                RedirectUri = authCode.redirect_uri.Split('?')[0].ToLower(),
                ResponseType = authCode.response_type,
                UserID = authCode.userId,
                UserName = authCode.userName,
                UserRole = JsonConvert.SerializeObject(authCode.userRole),
                UserAvatar = authCode.userAvatar,
                UserGroup = UserDataGroups.System,
                CreateDate = new DateTime(authCode.timestamp)
            });

            _context.SaveChanges();

            _cache.Remove(code);

            return new RedirectResult(url);
        }

        [HttpGet]
        public IActionResult SignIn([FromQuery] OAuthSignInModel value)
        {
            #region 切换账号
            if (!string.IsNullOrWhiteSpace(value.toggle) &&
                    _context.Users.Any(x => x.UserName == value.toggle))
            {
                if (!_context.Apps.Any(x => x.AppKey.Equals(value.client_id)))
                {
                    return new NotFoundObjectResult("应用" + value.client_id + "不存在");
                }

                HttpContext.SignOutAsync().Wait();

                ViewBag.toggle = value.toggle;

                return View(value);
            } 
            #endregion

            if (!User.Identity.IsAuthenticated)
            {
                if (!_context.Apps.Any(x => x.AppKey.Equals(value.client_id)))
                {
                    return new NotFoundObjectResult("应用" + value.client_id + "不存在");
                }

                return View(value);
            }

            if (string.IsNullOrWhiteSpace(value.code))
            {
                value.code = MakeAuthCode(value.client_id,
                    value.scope, value.grantType, value.redirect_uri,
                    _tokenProvider.User, BuildRequestUri(value));
            }

            return Redirect("/OAuth/Consent?code=" + value.code);
        }

        [HttpPost]
        public IActionResult SignInPost(OAuthSignInPostModel value)
        {
            TenantUserModel user;
            try
            {
                user = _tenantUser.FindUser(value.userName, value.Pwd);
            }
            catch (ArgumentException ex)
            {
                return new OkObjectResult(ex.Message);
            }

            var ticket = _tenant.CreateTicket(user, value.client_id, UserDataGroups.System);

            if (!string.IsNullOrWhiteSpace(value.redirect_uri))
            {
                ticket.Properties.RedirectUri = value.redirect_uri;
                //ticket.Properties.ExpiresUtc = DateTimeOffset.Now.AddDays(30);
            }

            HttpContext.SignInAsync(ticket.Principal, ticket.Properties).Wait();

            var identities = _GetSignInIdentities();

            if(!identities.Any(x=>x.UserName.Equals(value.userName)))
            {
                identities.Add(new SignInIdentityModel()
                {
                    UserName = value.userName,
                    Avatar = user.Avatar,
                    Email = user.Email,
                    Role = user.Role
                });

                var str = JsonConvert.SerializeObject(identities);

                //str = _dp.Protect(str);

                HttpContext.Response.Cookies.Append(AppConst.IdentityKeys,
                    str, new CookieOptions()
                    {
                        HttpOnly = false
                    });
            }

            var code = MakeAuthCode(value.client_id, value.scope, value.grantType, value.redirect_uri,
                user, BuildRequestUri(value));

            return Redirect("/OAuth/SignIn?Code=" + code);
        }

        private string BuildRequestUri(OAuthSignInModel q)
        {
            return $"/OAuth/SignIn?scheme={q.scheme}&client_id={q.client_id}&redirect_uri={q.redirect_uri}&scope={q.scope}&nonce={q.nonce}&state={q.state}";
        }

        [HttpPost]
        public IActionResult SignOut(string code)
        {
            HttpContext.SignOutAsync().Wait();

            var authCode = _cache.Get<AuthorizationCode>(code);

            _cache.Remove(code);

            return Redirect(authCode.request_uri);
        }

        string MakeAuthCode(string client_id,
            string scope,
            string grantType,
            string redirect_uri,
            TenantUserModel user,
            string request_uri)
        {
            var authCode = new AuthorizationCode()
            {
                tenantId = _tenant.Id,
                tenantName = _tenant.Name,
                client_id = client_id,
                scope = scope,
                response_type = grantType,
                userId = user.ID,
                userName = user.Name,
                userRole = user.Role,
                request_uri = request_uri,
                userAvatar = user.Avatar
            };

            var claims = _tenant.CreateClaims(user, client_id, UserDataGroups.System);

            var token = _tokenProvider.CreateToken(_claims =>
            {
                _claims.AddRange(claims);
            });

            authCode.redirect_uri = redirect_uri +
                $"?access_token={token.access_token}&expires_in={token.expires_in}&token_type=${token.token_type}";

            var code = Guid.NewGuid().ToString("n");

            _cache.Set(code, authCode);

            return code;
        }

        List<SignInIdentityModel> _GetSignInIdentities()
        {
            var items = new List<SignInIdentityModel>();

            if (HttpContext.Request.Cookies.TryGetValue(AppConst.IdentityKeys,
                out string _identities))
            {
               // _identities = _dp.Unprotect(_identities);

                items = JsonConvert.DeserializeObject<List<SignInIdentityModel>>(_identities);
            }

            return items;
        }
    }
}

Views/OAuth/Consent.cshtml
@model AuthorizationCode
@{
    ViewData["Title"] = Model.tenantName;
    var code = Context.Request.Query["code"];
    var state = Context.Request.Query["state"];
    var client = ViewBag.client as OAuthApp.Data.App;
    var redirect_uri = new Uri(Model.redirect_uri);
    var cancelUri = redirect_uri.Scheme + "://" + redirect_uri.Authority + redirect_uri.AbsolutePath;
}
@if (Model != null)
{
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-4 offset-md-4 d-flex align-items-start justify-content-center border border-top-0 border-bottom-0"
             style="height: 100vh;">
            <div style="width:80%" class="mt-5">
                <div class="d-flex text-center">
                    <div class="w-50">
                        <div>
                            <img src="@Model.userAvatar" class="shadow-sm border border-2 p-1 rounded-circle" width="68px" onerror="this.src='/assets/user_default.png'" />
                        </div>
                        <h2 class="mt-3 mb-2">
                            @Model.userName
                        </h2>
                        <form asp-action="SignOut" asp-controller="OAuth">
                            <input type="hidden" name="code" value="@code" />
                            <button class="btn btn-white">切换账号</button>
                        </form>
                    </div>
                    <div class="d-flex align-items-center justify-content-center">
                        <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-arrows-right-left" viewBox="0 0 24 24" stroke-width="1" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                            <line x1="21" y1="7" x2="3" y2="7"></line>
                            <path d="M18 10l3 -3l-3 -3"></path>
                            <path d="M6 20l-3 -3l3 -3"></path>
                            <line x1="3" y1="17" x2="21" y2="17"></line>
                        </svg>
                    </div>
                    <div class="w-50">
                        <div>
                            <img src="@client.Logo" class="shadow-sm border border-2 p-1 rounded-circle" width="68px" onerror="this.src='/assets/app_default.png'" />
                        </div>
                        <div class="my-3">
                            <h1>@client.Name</h1>
                            <p class="mt-2">@client.Website</p>
                        </div>
                    </div>
                </div>

                <div class="hr-text hr-text-center hr-text-spaceless my-4 fs-5 fw-normal">
                    申请以下权限
                </div>

                <div class="my-4 border p-1">
                    <div class="list-group list-group-flush">
                        @foreach (var s in Model.scope.Split(' '))
                        {
                            <a href="#" class="list-group-item list-group-item-action">@s</a>
                        }
                    </div>
                </div>
                <form action="/OAuth/ConsentPost" method="post">
                    <input type="hidden" name="code" value="@code" />
                    <input type="hidden" name="state" value="@state" />
                    <div class="d-flex flex-column">
                        <button type="submit" class="btn btn-indigo">确认授权</button>
                        <a href="@cancelUri" class="btn btn-white my-3">撤销</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
        }

Views/OAuth/SignIn.cshtml
@model OAuthSignInModel
@{
    //var client = ViewBag.client as OAuthApp.Data.App;
    var toggle = ViewBag.toggle?.ToString();
}

<div ng-app="app" class="container">
    <div class="row" ng-cloak ng-controller="AppCtrl">

        @*<div class="text-center">
            <img src="@client.Logo" class="shadow-sm border border-2 p-1 rounded-circle" width="68px"
                 onerror="this.src='/assets/app_default.png'" />
            <div class="my-3">
                <h1>@client.Name</h1>
                <p class="mt-2">@client.Website</p>
            </div>
        </div>*@

        <div ng-if="!showSignInPanel" class="col-md-6 col-sm-12 bg-white border-start border-end pt-4 px-4"
             style="margin: auto; min-height: 100vh;">
            <div>
                <h4>选择账户</h4>
                <div class="list-group list-group-flush">
                    <div class="list-group-item d-flex justify-content-between align-items-center pr-0"
                         ng-repeat="x in accounts track by $index">
                        <a href="javascript:;" ng-click="signinByAccount(x)">{{x.UserName}}</a>
                        <span class="badge-pill">
                            <button class="btn btn-link text-dark btn-sm" type="button" ng-click="delAccount($index)">
                                X
                            </button>
                        </span>
                    </div>
                </div>
                <div class="d-grid">
                    <button type="button" ng-click="useOtherAccount()" class="btn btn-indigo mt-3">使用其他账户</button>
                    <a href="@Model.redirect_uri" class="btn btn-white my-3">返回</a>
                </div>
            </div>
        </div>

        <div ng-if="showSignInPanel" class="col-md-6 col-sm-12 bg-white border-start border-end pt-4 px-4"
             style="margin: auto; min-height: 100vh;">
            <h4 class="d-flex">
                <span class="w-100">登录</span>
                <button class="btn btn-sm border" ng-click="chooseAccount()" ng-if="accounts.length>0">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                         class="bi bi-ui-radios-grid" viewBox="0 0 16 16">
                        <path d="M3.5 15a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5zm9-9a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5zm0 9a2.5 2.5 0 1 1 0-5 2.5 2.5 0 0 1 0 5zM16 3.5a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0zm-9 9a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0zm5.5 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7zm-9-11a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm0 2a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z" />
                    </svg>
                </button>
            </h4>

            <form method="post" action="/OAuth/SignInPost">
                <input name="scheme" type="hidden" value="@Model.scheme" />
                <input name="client_id" type="hidden" value="@Model.client_id" />
                <input name="scope" type="hidden" value="@Model.scope" />
                <input name="nonce" type="hidden" value="@Model.nonce" />
                <input name="state" type="hidden" value="@Model.state" />
                <input name="grantType" type="hidden" value="@Model.grantType" />
                <input name="redirect_uri" type="hidden" value="@Model.redirect_uri" />

                <div class="mb-3" ng-show="!signinHint">
                    <label class="form-label" for="username">账号</label>
                    <input type="text" name="userName" ng-model="selectedAccount.UserName" class="form-control" />
                    <small class="form-text text-muted">请输入您的邮箱账号/手机号</small>
                </div>

                <div ng-if="signinHint">
                    <div class="text-center">
                        <img src="{{selectedAccount.Avatar}}" onerror="this.src='/assets/user.png'" class="border p-1 rounded-circle shadow my-3" width="64px" />
                    </div>
                    <div class="form-group text-center pt-3 text-muted">
                        <h1>{{selectedAccount.UserName}}</h1>
                    </div>
                </div>

                <div class="mb-3">
                    <label class="form-label" for="password">密码</label>
                    <input type="password" name="Pwd" class="form-control" (keyup)="keyUp($event)" ng-model="selectedAccount.Pwd" />
                </div>

                <div class="d-grid">
                    <button class="btn btn-indigo btn-block mt-3" type="submit" ng-click="submitSignIn()">
                        登录
                    </button>

                    <a href='@Model.redirect_uri' class="btn btn-white btn-block mt-3">返回</a>

                    @*<div *ngIf="!loginHintFlag&&logins.length>0" class="pt-3">
                        <small style="margin-top: .8rem;" class="text-muted">
                            <font>其他登录</font> -
                        </small>
                        <a href="javascript:void(0)" *ngFor="let x of logins" class="btn btn-light border btn-sm m-2"
                           (click)="doExternalLogin(x)">{{x}}</a>
                    </div>*@
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{
    <script type="text/javascript">
        var app = angular.module('app', []);

        app.controller('AppCtrl', ['$scope', '$timeout', async function ($scope, $timeout) {
            $scope.signinHint = false;
            $scope.showSignInPanel = false;
            $scope.accounts = JSON.parse(Cookies.get("_IdentityKeys") || "[]");
            $scope.showSignInPanel = $scope.accounts.length < 1;

            $scope.selectedAccount = {};
            $scope.delAccount = function (_index) {
                delete $scope.accounts[_index];
                $scope.accounts = $scope.accounts.filter(x => x);

                Cookies.set('_IdentityKeys', JSON.stringify($scope.accounts),
                    {
                        expires: 2678400
                    });

                $scope.showSignInPanel = $scope.accounts.length < 1;
            }

            $scope.signinByAccount = function (_account) {
                $timeout(() => {
                    $scope.showSignInPanel = true;
                    $scope.signinHint = true;
                    $scope.selectedAccount = _account;
                }, 1)
            }

            $scope.chooseAccount = function () {
                $timeout(() => {
                    $scope.showSignInPanel = false;
                }, 1)
            }

            $scope.useOtherAccount = function () {
                $timeout(() => {
                    $scope.showSignInPanel = true;
                    $scope.selectedAccount = {};
                    $scope.signinHint = false;
                }, 1)
            }


            @if (!string.IsNullOrWhiteSpace(toggle))
            {
                @Html.Raw("$scope.signinByAccount($scope.accounts.filter(x => x.UserName = '" + toggle + "')[0] || {UserName:'" + toggle + "'})")
            }

            }]);
    </script>
}

Views/OAuth/UserInfo.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}